server:
  port: 8189
  servlet:
    context-path: /logistic
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=trucking
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false